# Generated by Django 5.2.4 on 2025-07-19 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, null=True, verbose_name='خطاب التقديم')),
                ('resume', models.FileField(blank=True, null=True, upload_to='application_resumes/', verbose_name='السيرة الذاتية')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='رابط الأعمال')),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='الراتب المتوقع')),
                ('availability_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوفر')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('reviewed', 'تمت المراجعة'), ('shortlisted', 'في القائمة المختصرة'), ('interview_scheduled', 'تم تحديد موعد المقابلة'), ('interview_completed', 'تمت المقابلة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('withdrawn', 'منسحب')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employer_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات صاحب العمل')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='التقييم')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='تمت المشاهدة')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المشاهدة')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL, verbose_name='المتقدم')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', verbose_name='الوظيفة')),
            ],
            options={
                'verbose_name': 'طلب توظيف',
                'verbose_name_plural': 'طلبات التوظيف',
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'applicant')},
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('phone', 'مقابلة هاتفية'), ('video', 'مقابلة فيديو'), ('in_person', 'مقابلة شخصية'), ('technical', 'مقابلة تقنية'), ('hr', 'مقابلة موارد بشرية')], max_length=20, verbose_name='نوع المقابلة')),
                ('scheduled_date', models.DateTimeField(verbose_name='تاريخ المقابلة')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='مدة المقابلة (بالدقائق)')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='مكان المقابلة')),
                ('meeting_link', models.URLField(blank=True, null=True, verbose_name='رابط الاجتماع')),
                ('interviewer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المقابل')),
                ('interviewer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد المقابل')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('completed', 'مكتملة'), ('cancelled', 'ملغية'), ('rescheduled', 'معاد جدولتها')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='التقييم')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='النتيجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.jobapplication', verbose_name='طلب التوظيف')),
            ],
            options={
                'verbose_name': 'مقابلة',
                'verbose_name_plural': 'المقابلات',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('reviewed', 'تمت المراجعة'), ('shortlisted', 'في القائمة المختصرة'), ('interview_scheduled', 'تم تحديد موعد المقابلة'), ('interview_completed', 'تمت المقابلة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('withdrawn', 'منسحب')], max_length=20, verbose_name='الحالة السابقة')),
                ('new_status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('reviewed', 'تمت المراجعة'), ('shortlisted', 'في القائمة المختصرة'), ('interview_scheduled', 'تم تحديد موعد المقابلة'), ('interview_completed', 'تمت المقابلة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('withdrawn', 'منسحب')], max_length=20, verbose_name='الحالة الجديدة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التغيير')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.jobapplication', verbose_name='طلب التوظيف')),
            ],
            options={
                'verbose_name': 'تاريخ حالة طلب التوظيف',
                'verbose_name_plural': 'تاريخ حالات طلبات التوظيف',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='application_attachments/', verbose_name='مرفق')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_application_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='applications.jobapplication', verbose_name='طلب التوظيف')),
            ],
            options={
                'verbose_name': 'رسالة طلب توظيف',
                'verbose_name_plural': 'رسائل طلبات التوظيف',
                'ordering': ['sent_at'],
            },
        ),
    ]
