# Generated by Django 5.2.4 on 2026-01-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مقروءة'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='scheduled_date',
            field=models.DateTimeField(db_index=True, verbose_name='تاريخ المقابلة'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'مجدولة'), ('completed', 'مكتملة'), ('cancelled', 'ملغية'), ('rescheduled', 'معاد جدولتها')], db_index=True, default='scheduled', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('reviewed', 'تمت المراجعة'), ('shortlisted', 'في القائمة المختصرة'), ('interview_scheduled', 'تم تحديد موعد المقابلة'), ('interview_completed', 'تمت المقابلة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('withdrawn', 'منسحب')], db_index=True, default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
