# Generated by Django 5.2.4 on 2026-01-01 20:27

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_applicationmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='application_attachments/', validators=[core.validators.validate_file_extension], verbose_name='مرفق'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='application_resumes/', validators=[core.validators.validate_document_extension], verbose_name='السيرة الذاتية'),
        ),
    ]
