# Generated by Django 5.2.4 on 2026-01-05 01:10

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_applicationmessage_attachment_and_more'),
        ('job_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='filled_template',
            field=models.FileField(blank=True, null=True, upload_to='application_filled_templates/', validators=[core.validators.validate_document_extension], verbose_name='الملف المعبأ'),
        ),
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('reviewed', 'تمت المراجعة'), ('shortlisted', 'في القائمة المختصرة'), ('interview_scheduled', 'تم تحديد موعد المقابلة'), ('interview_completed', 'تمت المقابلة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('withdrawn', 'منسحب'), ('external_redirect', 'تم التوجيه لتقديم خارجي')], max_length=20, verbose_name='الحالة الجديدة'),
        ),
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='old_status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('reviewed', 'تمت المراجعة'), ('shortlisted', 'في القائمة المختصرة'), ('interview_scheduled', 'تم تحديد موعد المقابلة'), ('interview_completed', 'تمت المقابلة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('withdrawn', 'منسحب'), ('external_redirect', 'تم التوجيه لتقديم خارجي')], max_length=20, verbose_name='الحالة السابقة'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('reviewed', 'تمت المراجعة'), ('shortlisted', 'في القائمة المختصرة'), ('interview_scheduled', 'تم تحديد موعد المقابلة'), ('interview_completed', 'تمت المقابلة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('withdrawn', 'منسحب'), ('external_redirect', 'تم التوجيه لتقديم خارجي')], db_index=True, default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='ApplicationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='الإجابة النصية')),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='application_responses/', validators=[core.validators.validate_file_extension], verbose_name='الملف المرفق')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='applications.jobapplication', verbose_name='طلب التوظيف')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='job_forms.jobformquestion', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'إجابة طلب',
                'verbose_name_plural': 'إجابات الطلبات',
                'unique_together': {('application', 'question')},
            },
        ),
    ]
