# Generated by Django 5.2.4 on 2025-07-19 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط المختصر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الفئة')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='أيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'فئة وظيفة',
                'verbose_name_plural': 'فئات الوظائف',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الوظيفة')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط المختصر')),
                ('description', models.TextField(verbose_name='وصف الوظيفة')),
                ('requirements', models.TextField(verbose_name='متطلبات الوظيفة')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='المسؤوليات')),
                ('benefits', models.TextField(blank=True, null=True, verbose_name='المزايا')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='المهارات المطلوبة')),
                ('job_type', models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('contract', 'عقد مؤقت'), ('freelance', 'عمل حر'), ('internship', 'تدريب')], max_length=20, verbose_name='نوع الوظيفة')),
                ('experience_level', models.CharField(choices=[('entry', 'مبتدئ (0-2 سنة)'), ('junior', 'مبتدئ متقدم (2-4 سنوات)'), ('mid', 'متوسط (4-7 سنوات)'), ('senior', 'خبير (7-10 سنوات)'), ('expert', 'خبير متقدم (10+ سنوات)')], max_length=20, verbose_name='مستوى الخبرة')),
                ('education_level', models.CharField(choices=[('high_school', 'ثانوية عامة'), ('diploma', 'دبلوم'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه'), ('any', 'غير محدد')], default='any', max_length=20, verbose_name='المستوى التعليمي')),
                ('city', models.CharField(choices=[('sanaa', 'صنعاء'), ('aden', 'عدن'), ('taiz', 'تعز'), ('hodeidah', 'الحديدة'), ('ibb', 'إب'), ('dhamar', 'ذمار'), ('mukalla', 'المكلا'), ('remote', 'عمل عن بُعد')], max_length=50, verbose_name='المدينة')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأدنى للراتب')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأعلى للراتب')),
                ('is_salary_negotiable', models.BooleanField(default=False, verbose_name='الراتب قابل للتفاوض')),
                ('application_deadline', models.DateTimeField(blank=True, null=True, verbose_name='آخر موعد للتقديم')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد التواصل')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف التواصل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='عاجل')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company', verbose_name='الشركة')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL, verbose_name='منشور بواسطة')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.jobcategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'وظيفة',
                'verbose_name_plural': 'الوظائف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التنبيه')),
                ('keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='الكلمات المفتاحية')),
                ('city', models.CharField(blank=True, choices=[('sanaa', 'صنعاء'), ('aden', 'عدن'), ('taiz', 'تعز'), ('hodeidah', 'الحديدة'), ('ibb', 'إب'), ('dhamar', 'ذمار'), ('mukalla', 'المكلا'), ('remote', 'عمل عن بُعد')], max_length=50, null=True, verbose_name='المدينة')),
                ('job_type', models.CharField(blank=True, choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('contract', 'عقد مؤقت'), ('freelance', 'عمل حر'), ('internship', 'تدريب')], max_length=20, null=True, verbose_name='نوع الوظيفة')),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'مبتدئ (0-2 سنة)'), ('junior', 'مبتدئ متقدم (2-4 سنوات)'), ('mid', 'متوسط (4-7 سنوات)'), ('senior', 'خبير (7-10 سنوات)'), ('expert', 'خبير متقدم (10+ سنوات)')], max_length=20, null=True, verbose_name='مستوى الخبرة')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأدنى للراتب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='إشعارات البريد الإلكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobcategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'تنبيه وظيفة',
                'verbose_name_plural': 'تنبيهات الوظائف',
            },
        ),
        migrations.CreateModel(
            name='JobBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحفظ')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='jobs.job', verbose_name='الوظيفة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_jobs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'وظيفة محفوظة',
                'verbose_name_plural': 'الوظائف المحفوظة',
                'unique_together': {('user', 'job')},
            },
        ),
    ]
