# Generated by Django 5.2.4 on 2026-01-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(choices=[('sanaa', 'صنعاء'), ('aden', 'عدن'), ('abyan', 'أبين'), ('amran', 'عمران'), ('al_bayda', 'البيضاء'), ('al_hudaydah', 'الحديدة'), ('al_jawf', 'الجوف'), ('al_maharah', 'المهرة'), ('al_mahwit', 'المحويت'), ('dhamar', 'ذمار'), ('hadhramaut', 'حضرموت'), ('hajjah', 'حجة'), ('ibb', 'إب'), ('lahij', 'لحج'), ('marib', 'مأرب'), ('raymah', 'ريمة'), ('saada', 'صعدة'), ('shabwah', 'شبوة'), ('socotra', 'سقطرى'), ('taiz', 'تعز'), ('remote', 'عمل عن بُعد')], db_index=True, max_length=50, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='job',
            name='education_level',
            field=models.CharField(choices=[('high_school', 'ثانوية عامة'), ('diploma', 'دبلوم'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه'), ('any', 'غير محدد')], db_index=True, default='any', max_length=20, verbose_name='المستوى التعليمي'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'مبتدئ (0-2 سنة)'), ('junior', 'مبتدئ متقدم (2-4 سنوات)'), ('mid', 'متوسط (4-7 سنوات)'), ('senior', 'خبير (7-10 سنوات)'), ('expert', 'خبير متقدم (10+ سنوات)')], db_index=True, max_length=20, verbose_name='مستوى الخبرة'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مميز'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_urgent',
            field=models.BooleanField(db_index=True, default=False, verbose_name='عاجل'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('contract', 'عقد مؤقت'), ('freelance', 'عمل حر'), ('internship', 'تدريب')], db_index=True, max_length=20, verbose_name='نوع الوظيفة'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='عنوان الوظيفة'),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='city',
            field=models.CharField(blank=True, choices=[('sanaa', 'صنعاء'), ('aden', 'عدن'), ('abyan', 'أبين'), ('amran', 'عمران'), ('al_bayda', 'البيضاء'), ('al_hudaydah', 'الحديدة'), ('al_jawf', 'الجوف'), ('al_maharah', 'المهرة'), ('al_mahwit', 'المحويت'), ('dhamar', 'ذمار'), ('hadhramaut', 'حضرموت'), ('hajjah', 'حجة'), ('ibb', 'إب'), ('lahij', 'لحج'), ('marib', 'مأرب'), ('raymah', 'ريمة'), ('saada', 'صعدة'), ('shabwah', 'شبوة'), ('socotra', 'سقطرى'), ('taiz', 'تعز'), ('remote', 'عمل عن بُعد')], max_length=50, null=True, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='اسم الفئة'),
        ),
    ]
