# Generated by Django 5.2.4 on 2026-01-05 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_forms', '0001_initial'),
        ('jobs', '0002_alter_job_city_alter_job_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد التقديم'),
        ),
        migrations.AddField(
            model_name='job',
            name='application_method',
            field=models.CharField(choices=[('platform', 'النظام الافتراضي للمنصة'), ('custom_form', 'استبيان مخصص'), ('template_file', 'قالب ملف'), ('external_link', 'رابط خارجي'), ('email', 'بريد الشركة')], default='platform', max_length=20, verbose_name='طريقة التقديم'),
        ),
        migrations.AddField(
            model_name='job',
            name='application_template',
            field=models.FileField(blank=True, null=True, upload_to='job_templates/', verbose_name='قالب طلب التوظيف'),
        ),
        migrations.AddField(
            model_name='job',
            name='custom_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='job_forms.jobform', verbose_name='الاستبيان المخصص'),
        ),
        migrations.AddField(
            model_name='job',
            name='external_application_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط التقديم الخارجي'),
        ),
    ]
