# Generated by Django 5.2.4 on 2026-01-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_application_email_job_application_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ai_summary',
            field=models.TextField(blank=True, null=True, verbose_name='ملخص الذكاء الاصطناعي'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_ai_summary_enabled',
            field=models.BooleanField(default=False, verbose_name='تفعيل تلخيص الذكاء الاصطناعي'),
        ),
    ]
