# Generated by Django 5.2.4 on 2025-07-19 23:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('job_seeker', 'باحث عن عمل'), ('employer', 'صاحب عمل'), ('admin', 'مدير')], default='job_seeker', max_length=20, verbose_name='نوع المستخدم')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='صورة الملف الشخصي')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة شخصية')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموقع')),
                ('is_verified', models.BooleanField(default=False, verbose_name='مُتحقق منه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('company_description', models.TextField(blank=True, null=True, verbose_name='وصف الشركة')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='شعار الشركة')),
                ('company_website', models.URLField(blank=True, null=True, verbose_name='موقع الشركة')),
                ('company_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='حجم الشركة')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='القطاع')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة التأسيس')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف صاحب عمل',
                'verbose_name_plural': 'ملفات أصحاب العمل',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='السيرة الذاتية')),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'مبتدئ (0-2 سنة)'), ('junior', 'مبتدئ متقدم (2-4 سنوات)'), ('mid', 'متوسط (4-7 سنوات)'), ('senior', 'خبير (7-10 سنوات)'), ('expert', 'خبير متقدم (10+ سنوات)')], max_length=20, null=True, verbose_name='مستوى الخبرة')),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'ثانوية عامة'), ('diploma', 'دبلوم'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه')], max_length=20, null=True, verbose_name='المستوى التعليمي')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='المهارات')),
                ('expected_salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأدنى للراتب المتوقع')),
                ('expected_salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأعلى للراتب المتوقع')),
                ('availability', models.BooleanField(default=True, verbose_name='متاح للعمل')),
                ('preferred_job_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الوظيفة المفضل')),
                ('languages', models.TextField(blank=True, null=True, verbose_name='اللغات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف باحث عن عمل',
                'verbose_name_plural': 'ملفات الباحثين عن عمل',
            },
        ),
    ]
