# Generated by Django 5.2.4 on 2026-01-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='كود التحقق'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت انتهاء صلاحية كود التحقق'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='industry',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='القطاع'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='availability',
            field=models.BooleanField(db_index=True, default=True, verbose_name='متاح للعمل'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'ثانوية عامة'), ('diploma', 'دبلوم'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه')], db_index=True, max_length=20, null=True, verbose_name='المستوى التعليمي'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'مبتدئ (0-2 سنة)'), ('junior', 'مبتدئ متقدم (2-4 سنوات)'), ('mid', 'متوسط (4-7 سنوات)'), ('senior', 'خبير (7-10 سنوات)'), ('expert', 'خبير متقدم (10+ سنوات)')], db_index=True, max_length=20, null=True, verbose_name='مستوى الخبرة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مُتحقق منه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='000-000-000', max_length=20, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('job_seeker', 'باحث عن عمل'), ('employer', 'صاحب عمل'), ('admin', 'مدير')], db_index=True, default='job_seeker', max_length=20, verbose_name='نوع المستخدم'),
        ),
    ]
