# Generated by Django 5.2.4 on 2026-01-01 20:27

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', validators=[core.validators.validate_image_extension], verbose_name='شعار الشركة'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[core.validators.validate_document_extension], verbose_name='السيرة الذاتية'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[core.validators.validate_image_extension], verbose_name='صورة الملف الشخصي'),
        ),
    ]
