# Generated by Django 5.2.4 on 2026-01-03 15:26

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employerprofile_company_logo_and_more'),
        ('applications', '0003_alter_applicationmessage_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('certificate', 'شهادة أكاديمية'), ('training', 'شهادة دورة تدريبية'), ('project', 'مشروع'), ('recommendation', 'خطاب توصية'), ('award', 'جائزة أو تكريم'), ('other', 'أخرى')], db_index=True, max_length=20, verbose_name='نوع الوثيقة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('file', models.FileField(upload_to='profile_documents/', validators=[core.validators.validate_document_extension], verbose_name='الملف')),
                ('issued_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='الجهة المصدرة')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('visibility', models.CharField(choices=[('public', 'عام - يمكن لأي صاحب عمل المشاهدة'), ('private', 'خاص - فقط أنا'), ('employers_only', 'أصحاب العمل فقط - عند التقديم')], db_index=True, default='employers_only', max_length=20, verbose_name='مستوى الخصوصية')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.jobseekerprofile', verbose_name='ملف الباحث عن عمل')),
            ],
            options={
                'verbose_name': 'وثيقة ملف شخصي',
                'verbose_name_plural': 'وثائق الملفات الشخصية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المشاهدة')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_views', to='applications.jobapplication', verbose_name='طلب التوظيف')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='المشاهد')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_views', to='accounts.profiledocument', verbose_name='الوثيقة')),
            ],
            options={
                'verbose_name': 'مشاهدة وثيقة',
                'verbose_name_plural': 'مشاهدات الوثائق',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
