# Generated by Django 5.2.4 on 2025-07-19 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط المختصر')),
                ('description', models.TextField(verbose_name='وصف الشركة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='شعار الشركة')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='company_covers/', verbose_name='صورة الغلاف')),
                ('website', models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(default='اليمن', max_length=100, verbose_name='البلد')),
                ('size', models.CharField(choices=[('startup', 'ناشئة (1-10 موظفين)'), ('small', 'صغيرة (11-50 موظف)'), ('medium', 'متوسطة (51-200 موظف)'), ('large', 'كبيرة (201-1000 موظف)'), ('enterprise', 'مؤسسة (1000+ موظف)')], max_length=20, verbose_name='حجم الشركة')),
                ('industry', models.CharField(choices=[('technology', 'تقنية المعلومات'), ('healthcare', 'الرعاية الصحية'), ('education', 'التعليم'), ('finance', 'المالية والمصرفية'), ('construction', 'البناء والتشييد'), ('retail', 'التجارة والبيع بالتجزئة'), ('manufacturing', 'التصنيع'), ('telecommunications', 'الاتصالات'), ('other', 'أخرى')], max_length=50, verbose_name='القطاع')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة التأسيس')),
                ('employees_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الموظفين')),
                ('is_verified', models.BooleanField(default=False, verbose_name='شركة موثقة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='شركة مميزة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المتابعة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='companies.company', verbose_name='الشركة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_companies', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'متابع شركة',
                'verbose_name_plural': 'متابعو الشركات',
                'unique_together': {('company', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 نجمة'), (2, '2 نجمة'), (3, '3 نجوم'), (4, '4 نجوم'), (5, '5 نجوم')], verbose_name='التقييم')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المراجعة')),
                ('review_text', models.TextField(verbose_name='نص المراجعة')),
                ('pros', models.TextField(blank=True, null=True, verbose_name='الإيجابيات')),
                ('cons', models.TextField(blank=True, null=True, verbose_name='السلبيات')),
                ('is_current_employee', models.BooleanField(default=False, verbose_name='موظف حالي')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفي')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='companies.company', verbose_name='الشركة')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to=settings.AUTH_USER_MODEL, verbose_name='المراجع')),
            ],
            options={
                'verbose_name': 'مراجعة شركة',
                'verbose_name_plural': 'مراجعات الشركات',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'reviewer')},
            },
        ),
    ]
