# Generated by Django 5.2.4 on 2026-01-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(db_index=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('technology', 'تقنية المعلومات'), ('healthcare', 'الرعاية الصحية'), ('education', 'التعليم'), ('finance', 'المالية والمصرفية'), ('construction', 'البناء والتشييد'), ('retail', 'التجارة والبيع بالتجزئة'), ('manufacturing', 'التصنيع'), ('telecommunications', 'الاتصالات'), ('other', 'أخرى')], db_index=True, max_length=50, verbose_name='القطاع'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='شركة مميزة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='شركة موثقة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(choices=[('startup', 'ناشئة (1-10 موظفين)'), ('small', 'صغيرة (11-50 موظف)'), ('medium', 'متوسطة (51-200 موظف)'), ('large', 'كبيرة (201-1000 موظف)'), ('enterprise', 'مؤسسة (1000+ موظف)')], db_index=True, max_length=20, verbose_name='حجم الشركة'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='يمكن إدخال www.example.com دون http(s)', null=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='موافق عليه'),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 نجمة'), (2, '2 نجمة'), (3, '3 نجوم'), (4, '4 نجوم'), (5, '5 نجوم')], db_index=True, verbose_name='التقييم'),
        ),
    ]
