# Generated by Django 5.2.4 on 2026-01-01 20:27

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_city_alter_company_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_covers/', validators=[core.validators.validate_image_extension], verbose_name='صورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', validators=[core.validators.validate_image_extension], verbose_name='شعار الشركة'),
        ),
    ]
