# Generated by Django 5.2.4 on 2026-01-05 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_company_cover_image_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم النموذج')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف النموذج')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_forms', to='companies.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'نموذج تقديم مخصص',
                'verbose_name_plural': 'نماذج التقديم المخصصة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobFormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='نص السؤال')),
                ('help_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='نص مساعد')),
                ('question_type', models.CharField(choices=[('text', 'نص قصير'), ('textarea', 'نص طويل'), ('number', 'رقم'), ('select', 'خيار من متعدد'), ('checkbox', 'خانة اختيار'), ('file', 'ملف مرفق'), ('date', 'تاريخ')], default='text', max_length=20, verbose_name='نوع السؤال')),
                ('required', models.BooleanField(default=True, verbose_name='مطلوب')),
                ('options', models.TextField(blank=True, help_text='أدخل الخيارات مفصولة بفاصلة (فقط لنوع "خيار من متعدد")', null=True, verbose_name='الخيارات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='job_forms.jobform', verbose_name='النموذج')),
            ],
            options={
                'verbose_name': 'سؤال نموذج',
                'verbose_name_plural': 'أسئلة النماذج',
                'ordering': ['order'],
            },
        ),
    ]
